### ISSUE TITLE
Integrate (or do not conflict) with Kubernetes Intellij Plugin

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2396]
(copied from `container-tools`, posted by another user)
Currently Jetbrains officially provides [Kubernetes Plugin](https://plugins.jetbrains.com/plugin/10485-kubernetes) which offers autocompletion and code inspection for Kubernetes resources yaml files. 

Given following ```skaffold.yaml``` file,

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: joelhandwell/kotlin-jvm-hello
deploy:
  kubectl:
    manifests:
    - k8s-*
profiles:
  - name: gcb
      googleCloudBuild:
        projectId: k8s-skaffold
```

As skaffold.yaml file syntax is very similar to kubernetes resource yaml file the file inspections defined for kubernetes resources triggered against skaffold.yaml too with inspection warnings.

```
Value 'skaffold/v1alpha2' is not expected here less... (Ctrl+F1) 
Inspection info: This inspection finds unrecognized values in Kubernetes resource definition files and highlights them in the editor.
```

```
Value 'Config' is not expected here less... (Ctrl+F1) 
Inspection info: This inspection finds unrecognized values in Kubernetes resource definition files and highlights them in the editor.
```

```
Key 'deploy' is not expected here less... (Ctrl+F1) 
Inspection info: This inspection finds unrecognized keys in Kubernetes resource definition files and highlights them in the editor.
```

```
Key 'profiles' is not expected here less... (Ctrl+F1) 
Inspection info: This inspection finds unrecognized keys in Kubernetes resource definition files and highlights them in the editor.
```

Screenshot looks like following:

![image](https://user-images.githubusercontent.com/3857152/44596778-7e90fa00-a79b-11e8-8b05-ce4c8cddb068.png)

Possible solution could be adding inspection which is only applied to ```skaffold.yaml``` at the same time disabling Kubernetes plugin inspection. 

P.S. for those who want to suppress Intellij kubernetes plugin warning against ```skaffold.yaml``` file, you can [click the Hector icon](https://stackoverflow.com/questions/36720296/idea-ide-disable-inspection-for-one-file) and change inspection level to syntax only on the file.
