### ISSUE TITLE
Issues with Multi-Module Maven Projects

### ISSUE THREAD

**Issue by Alos** [GoogleCloudPlatform/cloud-code-intellij#2499]
(Please ensure you are running the latest version of Cloud Code for IntelliJ with _Help > Check for Updates_)
- Cloud Code for IntelliJ version: 19.4.1
- Google Cloud SDK version: 241.0.0
- OS: Mac OS X 10.14.3

**What did you do?**
Try to use Skaffold with my Spring Boot application. 

0. Installed and configured all the requirements and installed the plugin
1. Added a small configuration in my skaffold.yaml
```
apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
    - image: gcr.io/myrepo/myimage
      jibMaven: {}
```
2. Clicked on the `Develop on Kubernetes` button

**What did you expect to see?**
Skaffold getting kicked in, building the app, then the image, pushing it to my K8s cluster.

**What did you see instead?**
```
skaffold dev --filename my-service/skaffold.yaml --label ide=idea --label ideVersion=2019.1.0.0 --label ijPluginVersion=unknown
...
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.0.2:_skaffold-files (default-cli): Goal requires a project to execute but there is no POM in this directory (/Users/myuser/Documents/Idea Workspace). 

Please verify you invoked Maven from the correct directory. -> [Help 1]\n[ERROR] \n[ERROR] 
```
As you can see, the plugin was unable to detect my project's directory. This is a single IntelliJ project that contains multiple Maven Modules.

**Comment by ivanporty** [comment]
We are working on adding better intelligence and generation support for Jib and detection modules / images. In the meanwhile, the structure of the `skaffold.yaml` for multi-module project should in general look similar to the following:

```yaml
  artifacts:
  - image: java-guestbook-backend
    jibMaven:
      module: backend
  - image: java-guestbook-frontend
    jibMaven:
      module: frontend
```

**Comment by ivanporty** [comment]
This is an excellent place to start as well and it has the full structure set up:
https://github.com/GoogleContainerTools/skaffold/tree/master/examples/jib-multimodule

**Comment by Alos** [comment]
Using module does not actually work. However I was able to place a `skaffold.yaml` at the root of my project and then do something like:
```yaml
apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: gcr.io/myproject/dog-service
    context: dog-service-directory
    jibMaven: {}
```
This build my app, created my image and pushed it to the registry.  But then:

```
Starting deploy...
time="2019-04-12T14:22:48-07:00" level=warning msg="k8s/*.yaml did not match any file"
kubectl client version: 1.11+
kubectl version 1.12.0 or greater is recommended for use with Skaffold
Deploy complete in 173.734895ms
Watching for changes every 1s...
time="2019-04-12T14:22:52-07:00" level=warning msg="k8s/*.yaml did not match any file"
time="2019-04-12T14:22:55-07:00" level=warning msg="k8s/*.yaml did not match any file"
Cleaning up...
time="2019-04-12T14:22:57-07:00" level=warning msg="k8s/*.yaml did not match any file"
time="2019-04-12T14:22:57-07:00" level=warning msg="k8s/*.yaml did not match any file"
No resources found
Cleanup complete in 65.548698ms
```
