### ISSUE TITLE
Showing error on BackendConfig

### ISSUE THREAD

**Issue by WLun001** [GoogleCloudPlatform/cloud-code-intellij#2713]
(Please ensure you are running the latest version of Cloud Cloud for IntelliJ with _Help > Check for Updates_.)

- Cloud Code for IntelliJ version: 20.1.3
- OS: MacOS 10.15.2

Currently on `BackendConfig`, it will detect as error and show red lines on IDE

Backend Config
```yaml
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: my-bsc-backendconfig
spec:
  timeoutSec: 600
  connectionDraining:
    drainingTimeoutSec: 60

```
![image](https://user-images.githubusercontent.com/23547929/74641381-27ab8b80-51ac-11ea-86a8-a52053d27649.png)

**Comment by WLun001** [comment]
Same goes to ManagedCertificate

```yaml
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: sample-certificate
```

![image](https://user-images.githubusercontent.com/23547929/74641795-d780f900-51ac-11ea-96b4-27bb7edd039d.png)
