### ISSUE TITLE
Cloud Code doesn't autocomplete latest skaffold schema

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/cloud-code-intellij#2722]
(Please ensure you are running the latest version of Cloud Cloud for IntelliJ with _Help > Check for Updates_.)

- Cloud Code for IntelliJ version: 20200317
- OS: macOS Catalina

**What did you do?**
1. Use Jib plugin in pom.xml
1. Cloud Code > Add Kubernetes Support
1. Generated skaffold.yaml
1. There is no editor support for the generated skaffold.yaml

Skaffold 1.5.0, generated yaml looks like:
```
apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: demo
build:
  artifacts:
  - image: gcr.io/wise-coyote-827/jib-demo
    jib:
      project: com.example:demo
      args: ["-DskipTests"]
deploy:
  kubectl:
    manifests:
    - k8s/demo.yaml
    - k8s/postgres.yaml
```

**What did you expect to see?**
Editor support for Skaffold files

**What did you see instead?**
No editor support.
Changing the apiVersion from v2alpha4 to v1 enabled the editor support again.

Why did skaffold generate a file that isn't editable in Cloud Code?
