### ISSUE TITLE
Multi Module maven cannot select Skaffold.yaml in root directory

### ISSUE THREAD

**Issue by mhn10** [GoogleCloudPlatform/cloud-code-intellij#2729]
- Cloud Code for IntelliJ version: 20.2.1
- OS: Mac OS 10.15.3
- Intellij 2019.3

**What did you do?**
I have 3 spring boot services in the following directory format
  ```bash
  ├── service-1
  ├── service-2
  ├── service-3
  └── skaffold.yaml
  ```
My skaffold.yaml file builds each of the services 

```yaml
build:
  artifacts:
  - image: service1-im
    context: service1
    jib:
      project: com.myservice:service1
  - image: service2-im
    context: service2
    jib:
      project: com.myservice:service2 
  - image: service3-im
    context: service3
    jib:
      project: com.myservice:service3
```
I'm able to run all 3 services using `skaffold run` via the terminal from the root directory that contains skaffold.yaml

**What did you expect to see?**
When I go into edit configuration > add Cloud Code  > skaffold configuration,  should show my `skaffold.yaml` file in the root directory

**What did you see instead?**
I'm only able to see the skaffold.yaml files that are present in the individual service directory, not the skaffold file in the root directory from which I can run/debug all the 3 services.
