### ISSUE TITLE
Cloud Code develop Cloud Run locally

### ISSUE THREAD

**Issue by Kevintjeb** [GoogleCloudPlatform/cloud-code-intellij#2818]
### Expected Behavior
Running locally starts the Cloud Run container

### Actual Behavior
Failure when preparing Google Cloud SDK
![image](https://user-images.githubusercontent.com/16103844/91823764-071fbc00-ec3a-11ea-93b0-8d5419d462e2.png)

### Additional Information

- IDE type : IntelliJ 2020.2.1
- Cloud Code version: 20.8.2-202
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK:  Yes
  - Version of the Cloud SDK: 307.0.0
- Operating System: MacOs Cataline 10.15.6 (19G2021)

![image](https://user-images.githubusercontent.com/16103844/91823086-fe7ab600-ec38-11ea-803b-8f1f4326325b.png)

I've found that when using my `local gcloud sdk`, it doens't have the 'setting up gcloud sdk', but it doesn't do anything either. It hangs forever..

**Comment by fsladkey** [comment]
Hey there @Kevintjeb, thanks for the report!

Sounds like a bug to me. I'm going to do some preliminary investigation and get back to you shortly with some troubleshooting steps. 

If by any chance you have a minimal version of the project to reproduce the problem that you're comfortable sharing with us we'd be happy to troubleshoot with you that way. If not, no problem I understand.

Hope to have this resolved for you soon!

**Comment by fsladkey** [comment]
To investigate the issue with the managed SDK, would you mind running the following command in your project directory and seeing if it succeeds, and if not how it fails? This is the command which appears to be failing in your original issue (and will use the Cloud Code managed SDK).

```
"/Users/<YOUR_USER_HERE>/Library/Application Support/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/bin/gcloud" alpha code export \
    --service-name dispatcher \
    --image dispatcher \
    --no-skaffold-file \
    --kubernetes-file ./export-test.yaml \
    --env-vars K_SERVICE=dispatcher,K_REVISION=local,K_CONFIGURATION=dispatcher \
     --memory 256MiB
```

If the command succeeds, it will create a yaml file in the location specified by `--kubernetes-file`, feel free to change the location.

As for the custom SDK hanging, I'm able to reproduce that, and I believe it is likely because the alpha components have not been installed. So another thing to try is to run `gcloud components install alpha`, then try again with your custom SDK. I'll file a bug to improve the error handling here regardless of whether that's the issue you're running into.

**Comment by Kevintjeb** [comment]
Thanks for the quick, extended response wow!

The supplied command works and generates : 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: dispatcher
  name: dispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      containers:
      - env:
        - name: PORT
          value: '8080'
        - name: K_CONFIGURATION
          value: dev
        - name: K_REVISION
          value: dev-0001
        - name: K_SERVICE
          value: dispatcher
        - name: K_CONFIGURATION
          value: dispatcher
        - name: K_REVISION
          value: local
        - name: K_SERVICE
          value: dispatcher
        image: dispatcher
        name: dispatcher-container
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 268435456
      terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  name: dispatcher
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: dispatcher
  type: LoadBalancer
```

However, the cloud code still fails with the same error. After I installed the alpha components I now also have the same error with the custom SDK.

Using Cloud Code in VsCode I received the following error:
```
,* Failed to start hyperkit VM. "minikube start -p cloud-run-dev-internal" may fix it: creating host: create: Error with pre-create check: "docker-machine-driver-hyperkit needs to run with elevated permissions. Please run the following command, then try again: sudo chown root:wheel /Users/kvandenbroek/.minikube/bin/docker-machine-driver-hyperkit && sudo chmod u+s /Users/kvandenbroek/.minikube/bin/docker-machine-driver-hyperkit"
,* 
,X error provisioning host: Failed to start host: creating host: create: Error with pre-create check: "docker-machine-driver-hyperkit needs to run with elevated permissions. Please run the following command, then try again: sudo chown root:wheel /Users/kvandenbroek/.minikube/bin/docker-machine-driver-hyperkit && sudo chmod u+s /Users/kvandenbroek/.minikube/bin/docker-machine-driver-hyperkit"
* 
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
```

it created the following launch.json
```
{
    "configurations": [
        {
            "name": "Cloud Run: Run/Debug Locally",
            "type": "cloudcode.cloudrun",
            "request": "launch",
            "build": {
                "docker": {
                    "path": "cloud-run/dispatcher/Dockerfile"
                }
            },
            "image": "dispatcher",
            "service": {
                "name": "dispatcher",
                "containerPort": 8080,
                "resources": {
                    "limits": {
                        "memory": "256Mi"
                    }
                }
            },
            "target": {
                "minikube": {}
            },
            "watch": true
        }
    ]
}
```
