### ISSUE TITLE
skaffold portForward not working with multiple ports

### ISSUE THREAD

**Issue by ashraf-revo** [GoogleCloudPlatform/cloud-code-intellij#2926]
iam getting this logs   
```
Port forwarding Service/streamer in namespace default, remote port 80 -> 127.0.0.1:8082
Port forwarding service/rtsp in namespace default, remote port 554 -> 127.0.0.1:4503
Port forwarding pod/streamer-84c6b9567d-l8qqt in namespace default, remote port 5005 -> 127.0.0.1:5005
```

### Expected behavior
i expect service/rtsp to run on port 8083

### Actual behavior
but i found it run on another port 4503   this bug only happen when iam using intellj idea cloud code plugin

### Information
- IDE type IntelliJ:
- IDE version: 2021.1
- Skaffold version:  run `v1.16.0` 
- Operating system:  ubuntu 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: streamer
build:
  artifacts:
  - image: ashraf1abdelrasool/streamer
    context: .
    jib:
      project: org.revo:streamer
deploy:
  kubectl:
    manifests:
    - target/jkube/*.yml
portForward:
  - port: 80
    localPort: 8082
    resourceType: Service
    resourceName: streamer
  - port: 554
    localPort: 8083
    resourceType: Service
    resourceName: rtsp

```
