### ISSUE TITLE
Goland: Unable to select deployment profile

### ISSUE THREAD

**Issue by JCzz** [GoogleCloudPlatform/cloud-code-intellij#3038]
skaffold version
`v1.35.1`

Cloud Code plugin:
`22.11.213`

I have manually created a skaffold.yaml. 
`skaffold dev` works as expected, but if I try to add a configuration in Goland(Cloud Code: Kubernetes)  using this skaffold file i get the following error message in the configuration window: `Invalid Data: Select or create a skaffold profile on the Build/Deploy tab.` But I can not select any or create any profile, and there is already a profile in the skaffold.yaml ?

skaffold.yaml
```
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: test
build:
  artifacts:
  - image: dockerfile-image
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml
portForward:
- resourceType: service
  resourceName: dockerfile-image
  port: 80
profiles:
  - name: test
    build:
      local: {}
```
