### ISSUE TITLE
Not watching for change using Goland - but works using skaffold dev and with: error layer=rpc

### ISSUE THREAD

**Issue by JCzz** [GoogleCloudPlatform/cloud-code-intellij#3039]
skaffold version
```
skaffold version
v1.35.1
```

Cloud Code(Goland Cloud Code: Kubernetes: 
`21.11.2-213`

When using `skaffold dev`

```
Images loaded in 9.47 seconds
 - deployment.apps/dockerfile-image configured
Waiting for deployments to stabilize...
 - deployment/dockerfile-image is ready.
Deployments stabilized in 2.24 seconds
Port forwarding service/dockerfile-image in namespace default, remote port 80 -> http://127.0.0.1:4503
Watching for changes...
```

But when using Goland I get the following(no watching... and error layer=rpc) :
```
Waiting for deployments to stabilize...
 - pod/dockerfile-image-84ddbbf78-cgdqc: waiting for init container install-go-debug-support to start
 - deployment/dockerfile-image: 
 - pod/dockerfile-image-84ddbbf78-cgdqc: running.
 - deployment/dockerfile-image is ready.
Deployments stabilized in 7.385 seconds
Port forwarding service/dockerfile-image in namespace default, remote port 80 -> http://127.0.0.1:4504
Press Ctrl+C to exit
Not watching for changes...
[dockerfile-image] API server listening at: [::]:56268
[install-go-debug-support] Installing runtime debugging support files in /dbg
[install-go-debug-support] Installation complete
Port forwarding pod/dockerfile-image-84ddbbf78-cgdqc in namespace default, remote port 56268 -> http://127.0.0.1:56268
[dockerfile-image] 2021-12-06T21:58:30Z error layer=rpc writing response:write tcp [::1]:56268->[::1]:57360: use of closed network connection
```

This is the skaffold.yaml
```
apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: test
build:
  artifacts:
  - image: dockerfile-image
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml
portForward:
- resourceType: service
  resourceName: dockerfile-image
  port: 80
profiles:
  - name: test
    build:
      local: {}
```
