### ISSUE TITLE
Deploy fails apparently because the wrong project is being used

### ISSUE THREAD

**Issue by subfuzion** [GoogleCloudPlatform/cloud-code-intellij#3050]
Running into the [same issue](https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/520) trying to switch projects that I ran into with Visual Studio Code, except for Intellij, none of the workarounds seem to work.

### Expected Behavior

Working just fine in VSC:

![image](https://user-images.githubusercontent.com/159738/150765198-6c3884e7-ee0e-4371-939e-38a6e74238a3.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/159738/150764531-5074fdd6-20b9-46e6-be1c-9ac45d5dc901.png)

How does check (let alone switch) projects like in VSC...?

![image](https://user-images.githubusercontent.com/159738/150764987-69c6ac9a-f889-48e2-afba-c8f7e8b7a358.png)

### Additional Information

- IDE type: IntelliJ:
- IDE version: 2021.3.2 Preview
- Cloud Code version: 21.12.1-213
- Cloud SDK (Settings > Cloud Code > Cloud SDK): Don't see this info in Intellij on macOS 🤷🏻‍♂️ 
  - Are you allowing the plugin to manage the Cloud SDK: 🤷🏻‍♂️
  - Version of the Cloud SDK: 🤷🏻‍♂️
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): 🤷🏻‍♂️
- Operating System: macOS Monterey 12.1

**Comment by etanshaul** [comment]
hi @subfuzion thanks for the report. Let's try and dig into this:

I don't have enough info to tell myself, but are you thinking IntelliJ is deploying to the wrong project? The way you configure this in intellij is inside the Run Configuration options:
<img width="721" alt="Screen Shot 2022-01-24 at 10 21 43 AM" src="https://user-images.githubusercontent.com/1735744/150811221-a3341840-2b3e-45d4-9ff4-e68ee428b84b.png">

By default, IntelliJ will deploy to the currect active kubectl context. You can also override it with the last radio button and pin it to a context of your choosing.


Also, you mention this is working via the command line, but not in IntelliJ. Could you share the `skaffold dev` command being executed on the command line, and the one used by IntelliJ so that we can compare (the intellij command is printed at the top of the log - click on the root node in the deployment status tree on the left, then grab the command line from the log window on the right).

**Comment by subfuzion** [comment]
Hi @etanshaul, that's the Kubernetes context, but not necessarily the Google project. I do have that selected.

![image](https://user-images.githubusercontent.com/159738/150828788-441da176-4e4d-41f6-8576-ed49c1ca8b41.png)

Here's skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: election-app
build:
  artifacts:
  - image: gcr.io/election-app/web
    context: src/web
    docker:
      dockerfile: Dockerfile
  - image: gcr.io/voting-app/vote
    context: src/vote
    docker: {}
  tagPolicy:
    sha256: {}
  googleCloudBuild: {}
deploy:
  kubectl:
    manifests:
    - kubernetes/postgres.yaml
    - kubernetes/vote.yaml
    - kubernetes/web.yaml
```

And the command I used to run it in a terminal:

```text
export PROJECT_ID=tony-autopilot
skaffold dev -f skaffold.yaml --default-repo=gcr.io/$PROJECT_ID/voting-app --tail
```
