### ISSUE TITLE
Pycharm Cloud Code Debugger Not Working When Does Work In VS Code

### ISSUE THREAD

**Issue by ltieman** [GoogleCloudPlatform/cloud-code-intellij#3059]
(Please ensure you are running the latest version of Cloud Cloud IntelliJ with _Help > Check for Updates_.)

(screenshots are often helpful)

### Expected Behavior
Set Breakpoints in PyCharm trigger the debugger and send data properly to the debugger.

### Actual Behavior
Breakpoints are skipped past without catching.  Breakpoints declared with `import pydevd_pycharm; pydevd_pycharm.settrace()` are caught but the debugger receives no information from the breakpoint, and eventually the code will timeout, without any reaction from the debugger.  Both of these work in VSCode with the same configuration. 

Hard Coded Breakpoint In Code
![image](https://user-images.githubusercontent.com/1084689/155582575-af64d65d-1709-4eaa-9da5-c6e97fa75d27.png)
Stops Execution
![image](https://user-images.githubusercontent.com/1084689/155582381-f823ae42-10f5-479f-93e8-fbfea34ee566.png)
Variables in VSCode
![image](https://user-images.githubusercontent.com/1084689/155583085-bfafc3de-7f4e-46d7-ba2c-4e3c0b09c398.png)
Nothing in PyCharm
![image](https://user-images.githubusercontent.com/1084689/155583356-89625d7d-e28c-4b21-9adc-95aec0b4a501.png)
Soft Breakpoint in Code
![image](https://user-images.githubusercontent.com/1084689/155583556-bd2e617f-b31b-42ea-821c-df46862cff8d.png)
Breakpoint Skipped
![image](https://user-images.githubusercontent.com/1084689/155583834-546d9af0-38fc-4e93-8efd-6c7fcc0d1e3b.png)

### Additional Information
Skaffold Configuration:

```
apiVersion: skaffold/v2beta25
kind: Config
build:
  tagPolicy:
      customTemplate:
          template: "archive"
  artifacts:
  - image: main
    docker:
        dockerfile: Dockerfile.devtest
    hooks:
        before:
            - command: ["sh", "./ecr-login.sh"]
              os: [darwin, linux]
    sync:
        auto: false
        hooks:
            before:
                -   host:
                        command: ["sh", "./ecr-login.sh"]
                        os: [ darwin, linux ]
  - image: micro
    hooks:
        before:
            -   command: ["sh", "./ecr-login.sh" ]
                os: [darwin, linux]
    sync:
        auto: false
        hooks:
            before:
                -   host:
                        command: ["sh", "./ecr-login.sh" ]
                        os: [ darwin, linux ]
    context: ./modules/microservice
    docker:
        dockerfile: microservice.dockerfile
  local:
    useDockerCLI: true
    push: true
    concurrency: 0

deploy:
  helm:
    releases:
    - name: dev01
      chartPath: ./devops/auto-devops
      valuesFiles:
          - devops/auto-devops/values-dev-01.yaml
      artifactOverrides:
        imageMain: main
        imageMicro: micro
      imageStrategy:
          helm: { }
```

Working VSCode launch.json
```
{
    "configurations": [
        
        {
            "name": "Kubernetes: Run/Debug",
            "type": "cloudcode.kubernetes",
            "request": "launch",
            "skaffoldConfig": "${workspaceFolder}/skaffold-dev-01.yaml",
            "watch": true,
            "cleanUp": false,
            "portForward": true,
            "internalConsoleOptions": "neverOpen",
            "imageRegistry": "xxx",
            "debug": [
                {
                    "image": "ada-main",
                    "containerName": "ioa-api",
                    "sourceFileMap": {
                        "${workspaceFolder}": "/opt/ioa"
                    }
                }
            ]
        }
    ]
}
```

Pycharm Config:
![image](https://user-images.githubusercontent.com/1084689/155584061-7975964d-bbe5-4789-9638-f2831844c52c.png)
![image](https://user-images.githubusercontent.com/1084689/155584192-dfb9932b-901b-4c31-a495-ba63f9b7b049.png)
![image](https://user-images.githubusercontent.com/1084689/155584341-5222bb5c-e1ce-4da1-9497-d264bca1cf78.png)

- IDE type (e.g. IntelliJ, Pycharm): Pycharm Pro
- IDE version: 2021.3.2
- Cloud Code version (Settings > Plugins > Cloud Code): 22.2.1-213
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK:  yes
  - Version of the Cloud SDK: 22.2.1-213
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes):  1.35.2
- Operating System: macOS 11.6.4

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._
