### ISSUE TITLE
Unable to use Kubernetes Explorer without permission to read namespaces

### ISSUE THREAD

**Issue by horodchukanton** [GoogleCloudPlatform/cloud-code-intellij#3073]
### Expected Behavior
According to https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2697, the context's namespace should be used by default and I should see a list of deployments(/pods/replicasets?)

### Actual Behavior
Plugin fails to build a list of available namespaces, because I don't have a permission to list the namespaces.
<img width="637" alt="Знімок екрана 2022-04-13 о 13 40 43" src="https://user-images.githubusercontent.com/13728521/163163737-855a149d-c68d-4ca8-a74e-9e4948d875c7.png">

### Additional Information

- IDE type: **IntelliJ** (e.g. IntelliJ, Pycharm):
- IDE version: **IntelliJ IDEA 2022.1 (Ultimate Edition) Build #IU-221.5080.210**
- Cloud Code version: **22.3.1-213**
- Cloud SDK:
  - Are you allowing the plugin to manage the Cloud SDK: **yes**
  - Version of the Cloud SDK: 381.0.0
- Skaffold version: v1.36.1
- Operating System: MacOS Monterey 12.3 (Intel)

Context definition in .kube/config
```
  contexts:
  - context:
      cluster: te[hidden].com
      namespace: shipping
      user: oidc
    name: te[hidden].com
  current-context: te[hidden].com
```
