### ISSUE TITLE
Invalid Data: Skaffold configuration file doesn't exist or is invalid

### ISSUE THREAD

**Issue by yinyuncan** [GoogleCloudPlatform/cloud-code-intellij#3085]
### Expected Behavior
Unable to save configuration

### Actual Behavior

![image](https://user-images.githubusercontent.com/56066641/179344171-335f42e8-6f6b-45b2-85f1-e4baf30f9eba.png)

This is my configuration
```yaml
apiVersion: skaffold/v2beta19
kind: Config
build:
    tagPolicy:
        sha256: {}
    artifacts:
        - image: ym/park-2021
          context: ./

deploy:
    kubectl:
        manifests:
            - ./kubernetes-manifests/**.yaml
profiles:
    - name: cloudbuild
      build:
          googleCloudBuild: {}
    - name: dockerfile
      build:
          artifacts:
              - image: ym/park-2021
```

![image](https://user-images.githubusercontent.com/56066641/179344326-56d9bd25-5a82-48d8-bd6a-87582a4eeadb.png)

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): **IntelliJ**
- IDE version: **IntelliJ IDEA 2021.3 (Ultimate Edition)**
- Cloud Code version (Settings > Plugins > Cloud Code): **22.7.1**
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: 
  - Version of the Cloud SDK: 393.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes):  **1.39.1**
- Operating System: Windows10
