### ISSUE TITLE
Debugger does not re-attach after making changes and triggering a build and deploy

### ISSUE THREAD

**Issue by jpennell-ea** [GoogleCloudPlatform/cloud-code-intellij#3100]
### Expected Behavior

1. Click Debug, to run a Cloud Code Kubernetes run configuration with Watch Mode: On Demand, with attached debugger
2. Debugger is attached
4. Breakpoint has check mark
5. Set breakpoint
6. Trigger breakpoint by executing a curl command
7. Click resume program to continue
8. Make code changes to the file with the breakpoint in it
9. Click Trigger Build and Deploy button to refresh changes without redeploying
10. Debugger is attached
11. Breakpoint has a check mark
12. Breakpoint is triggered by executing a curl command
13. Click resume program to continue
14. Changes are reflected in the response

### Actual Behavior

1. Click Debug, to run a Cloud Code Kubernetes run configuration with Watch Mode: On Demand, with attached debugger (Works!)
    - ![image](https://user-images.githubusercontent.com/54281488/192846155-7bf593e5-5ea1-465f-819f-66914df62219.png)
    - ![image](https://user-images.githubusercontent.com/54281488/192846097-d0f7d594-6caa-432f-9683-1057113097dc.png)
3. Debugger is attached (Works!)
    - ![image](https://user-images.githubusercontent.com/54281488/192848438-ef09269d-513a-43b0-9741-29816b939c61.png)
    - ![image](https://user-images.githubusercontent.com/54281488/192848480-59eaabd4-009c-4bd7-87fa-f7342e486760.png)
4. Breakpoint has check mark (Works!)
    - ![image](https://user-images.githubusercontent.com/54281488/192848518-7ddfb311-60e1-4b46-9c5f-770ed4b780f2.png)
5. Set breakpoint (Works!)
    - ![image](https://user-images.githubusercontent.com/54281488/192846234-811e2c12-bd86-42c4-8beb-4b20c25f9c1b.png)
6. Trigger breakpoint by executing a curl command (Works!)
    - ![image](https://user-images.githubusercontent.com/54281488/192846307-9ac96d9d-68fb-420f-98df-c771ae65d4ca.png)
    - ![image](https://user-images.githubusercontent.com/54281488/192846371-5074f099-9641-4850-8a2f-195006e1a037.png)
7. Click resume program to continue (Works!)
    - ![image](https://user-images.githubusercontent.com/54281488/192846422-95f8009e-9b44-4c58-bd3b-641e35ae5296.png)
8. Make code changes to the file with the breakpoint in it (Works!)
    - ![image](https://user-images.githubusercontent.com/54281488/192846482-7e9c0260-3ca8-4bf4-bcea-8cb6cdd7ee30.png)
9. Click Trigger Build and Deploy button to refresh changes without redeploying (Works!)
    - ![image](https://user-images.githubusercontent.com/54281488/192847408-4d6d3af3-3a2f-4f84-bd7c-40db800eedae.png)
10. **Debugger is no longer attached.** (Not Working!)
    - ![image](https://user-images.githubusercontent.com/54281488/192847541-ec70bb00-31f5-46b6-b110-56bc7356be48.png)
11. **Breakpoint no longer has check mark** (Not Working!)
    - ![image](https://user-images.githubusercontent.com/54281488/192847772-4c3dee8c-fd52-407b-8895-497df1a1c8b9.png)
12. **Breakpoint is not triggered by executing a curl command** (Not Working!)
    - ![image](https://user-images.githubusercontent.com/54281488/192849218-8959bde4-0311-4783-92bf-32c2edb333a7.png)
13. Changes are reflected in the response (Works!)
    - ![image](https://user-images.githubusercontent.com/54281488/192850637-d587829f-67f8-4c1c-b8ac-3c62a240d5fe.png)

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): Intellij
- IDE version: 2022.2.2
- Cloud Code version (Settings > Plugins > Cloud Code): 22.9.3-222
    - ![image](https://user-images.githubusercontent.com/54281488/192849962-df496e54-85d1-452d-a548-f4e02019ec01.png)
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: Yes
  - Version of the Cloud SDK: 404.0.0
  - ![image](https://user-images.githubusercontent.com/54281488/192849677-d52eb566-967a-4f91-a8e4-75d5150a87d4.png)
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): v1.39.2
- Operating System: Windows 10 Enterprise Version 10.0.19044 Build 19044

**Comment by ivanporty** [comment]
Thanks @jpennell-ea for your report, we are looking into this

**Comment by jpennell-ea** [comment]
> Thanks @jpennell-ea for your report, we are looking into this

hey @ivanporty any update? Thanks!

**Comment by etanshaul** [comment]
hi @jpennell-ea we haven't had a chance to investigate this more yet. Could you provide any more details on the application your are debugging? Does it use Helm?

**Comment by jpennell-ea** [comment]
> hi @jpennell-ea we haven't had a chance to investigate this more yet. Could you provide any more details on the application you are debugging? Does it use Helm?

Hey @etanshaul, yes it does use helm! Here is our skaffold file.

```yaml
apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
  - image: my-app
    jib:
      project: app
    sync:
      auto: true
  tagPolicy:
    customTemplate:
      template: "{{.DATE}}_{{.GIT_SHA}}"
      components:
      - name: DATE
        dateTime:
          format: "2006-01-02"
          timezone: "Local"
      - name: GIT_SHA
        gitCommit:
          variant: AbbrevCommitSha
  local:
    push: false

deploy:
  kubeContext: docker-desktop
  helm:
    releases:
      - name: my-app-local
        chartPath: chart
        valuesFiles:
        - chart/values-env-local.yaml
        namespace: my-app-local
        artifactOverrides:
          image:  my-app
        setValueTemplates:
          image.tag: '{{.DIGEST_HEX}}'
        setValues:
          pullPolicy: IfNotPresent
          image.registry: ''
          image.repository: my-app
        imageStrategy:
          helm:
            explicitRegistry: false
        createNamespace: true
    flags:
      install:
      - --timeout=600s
      upgrade:
      - --timeout=600s
  statusCheckDeadlineSeconds: 600

portForward:
  # my-app http
  - resourceType: deployment
    resourceName: my-app-local-my-app-cf
    namespace: my-app-local
    address: 0.0.0.0
    port: 8080
    localPort: 10000
  # my-app http admin
  - resourceType: deployment
    resourceName: my-app-local-my-app-cf
    namespace: my-app-local
    address: 0.0.0.0
    port: 8081
    localPort: 10001
  # my-app grpc
  - resourceType: deployment
    resourceName: my-app-local-my-app-cf
    namespace: my-app-local
    address: 0.0.0.0
    port: 6565
    localPort: 10002

```
