### ISSUE TITLE
Yaml Language Server startup error

### ISSUE THREAD

**Issue by pasglop** [GoogleCloudPlatform/cloud-code-intellij#3140]
(Please ensure you are running the latest version of Cloud Cloud IntelliJ with _Help > Check for Updates_.)

(screenshots are often helpful)

### Expected Behavior
no freeze

### Actual Behavior
When I start webstorm I get this notification :

Yaml Language Server startup error

Request initialize failed with message: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")

Then after 1 to 5 mn webstorm freeze for ~5mn (Think waiting a time out)

This happens when Plugin Google Cloud Code is installed and activated (thus related). Also I have AWS toolkit plugin installed and activated.

I disabled the Google Cloud Code and the startup error disappeared.

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): webstorm
- IDE version: 2023.1.1
- Cloud Code version (Settings > Plugins > Cloud Code): 23.5.1-222
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: Yes
  - Version of the Cloud SDK:  418.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): v2.1.0
- Operating System: Windows 11

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

WebStorm 2023.1.1
Build #WS-231.8770.64, built on April 27, 2023
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    eslint.additional.file.extensions=svelte

Non-Bundled Plugins:
    net.chakmidlot.jetbrains.bigquery.plugin (0.1.3)
    org.intellij.plugins.hcl (231.8109.91)
    com.github.copilot (1.2.5.2507)
    com.intellij.ideolog (203.0.30.0)
    org.jetbrains.plugins.localization (231.8109.91)
    ru.adelf.idea.dotenv (2023.1)
    com.intellij.database (231.8770.64)
    com.github.dbDoc (0.1)
    com.intellij.lang.jsgraphql (4.0.0)
    dev.blachut.svelte.lang (231.8770.15)
    com.haulmont.rcb (2023.2-231)
    mdx.js (231.8109.91)
    aws.toolkit (1.67-231)

**Comment by etanshaul** [comment]
sorry for the delay here. is this still an issue? We are not able to repro this. There is a new version of the plugin you can try as well. `22.5.2`. Let us know if you are still facing this.

**Comment by jlenuffgsoi** [comment]
Hi, the bug is still present.
```
Request initialize failed with message: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")
```

Plugin version : 23.5.2-222
IDE : Intellij IDEA 2023.1.3 (Ultimate Edition), build #IU-231.9161.38

**Comment by etanshaul** [comment]
We are looking into this. Do you happen to know which Yaml file you had open when this error came up? If so, is it possible to share the contents (redacting sensitive info)?

**Comment by jlenuffgsoi** [comment]
This message show at Intellij startup. The title message is `Yaml Language Server startup error`.
So, it happens when scanning the whole local repository (not when openning a particular file).
I have several files, but only 5 YAML files.

One of these is :
```
services:
  jenkins:
    image: jenkins/jenkins:2.387.3-lts-jdk11
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: /mnt/disk/jenkins_data
        target: /var/jenkins_home
    environment:
      JAVA_OPTS: >-
        -Djava.awt.headless=true
        -Dhudson.model.DirectoryBrowserSupport.CSP="sandbox allow-scripts; default-src 'none'; img-src 'self' data: ; style-src 'self' 'unsafe-inline' data: ; script-src 'self' 'unsafe-inline' 'unsafe-eval';"
        -Dorg.apache.commons.jelly.tags.fmt.timeZone=Europe/Paris
volumes:
  jenkins_home:
```

And one other is :
```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: /secrets
      - id: check-added-large-files
      - id: check-yaml
        args:
        - '--allow-multiple-documents'
        exclude: /templates|/secrets

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.72.1
    hooks:
      - id: terraform_fmt
        args:
        - --args=-diff
        - --args=-write=true
      - id: terraform_docs
      - id: terraform_tflint
        files: \.tf$
        args:
        - '--args=--enable-rule=terraform_deprecated_interpolation'
        - '--args=--enable-rule=terraform_deprecated_index'
        - '--args=--enable-rule=terraform_unused_declarations'
        - '--args=--enable-rule=terraform_comment_syntax'
        - '--args=--enable-rule=terraform_documented_outputs'
        - '--args=--enable-rule=terraform_documented_variables'
        - '--args=--enable-rule=terraform_typed_variables'
        - '--args=--enable-rule=terraform_required_version'
        - '--args=--enable-rule=terraform_required_providers'
        - '--args=--enable-rule=terraform_unused_required_providers'
        - '--args=--enable-rule=terraform_standard_module_structure'
      # - id: terraform_tfsec
      #   args:
      #   - '--args=--config-file __GIT_WORKING_DIR__/.tfsec.yml --exclude-downloaded-modules --exclude-path=.tfsec/cache'
```

The others are very similar.
