### ISSUE TITLE
Cloud Code breaks multibyte? yaml editing

### ISSUE THREAD

**Issue by topia** [GoogleCloudPlatform/cloud-code-intellij#3151]
- Cloud Code for IntelliJ version: 23.6.3-IB.1-api-version-222
- Google Cloud SDK version: 438.0.0
- OS: Windows 11 10.0

**What did you do?**
Editing UTF-8 YAML containing Japanese text.

**What did you expect to see?**
No code problems are shown.

**What did you see instead?**
Many unexpected code problems are shown:
![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/13070/9ae7be04-a36b-4218-a407-a55052ec41cf)

YAML is basic and should be valid:
```yaml
test:
  key: value
  foo:
    key: value

  キー: 値

  bar:
    key2: value2
```

I tried this with IDEA 2023.2 Beta (Ultimate) `#IU-232.8660.48` only for now, and I don't know if it's related to Beta/EAP or not.

**Comment by topia** [comment]
I can't reproduce second time, so I slightly changed the steps to reproduce always:

1. create `test.yaml` and input below text:
```yaml
test:
  key: value
  foo:
    key: value

  キー: 値

  bar:
    key2: value2
```

2. moved to the beginning of line 2 and typed `&key `

```yaml
test:
  &key key: value
...
```

3. Cloud Code shows many errors for this valid input.

Maybe my issue subject was not correct, but it was caused by an already-broken internal state.
